---
title: "Proposal"
description: |
  Our project proposal showcases our scope, approach and methodology in tackling Mini-Challenge 2 of VAST Challenge 2021
author:
  - name: Kelly Koh Kia Woon
    url: google.com
    affiliation: School of Computing and Information Systems, Singapore Management University
    affiliation_url: https://scis.smu.edu.sg/
  - name: Manmit S/o Narmal Singh 
    url: google.com
    affiliation: School of Computing and Information Systems, Singapore Management University
    affiliation_url: https://scis.smu.edu.sg/
  - name: Syed Ahmad Zaki Bin Syed Sakaf Al-Attas 
    url: google.com
    affiliation: School of Computing and Information Systems, Singapore Management University
    affiliation_url: https://scis.smu.edu.sg/
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    self_contained: false
    code_folding: true
    toc: true
    toc_depth: 3
---

## Project Proposal  
Our project is based on Mini-Challenge 2 within VAST Challenge 2021, where it specifically deals with an analysis of movement and tracking data.  

### Steps Involved   
1.	Getting a better sense of the spatio temporal data (credit card, loyalty and GPS)
2.	Cleaning the data and choosing the best visualisations (maps or otherwise) for insight gathering
3.	Allowing pre-determined inputs to allow flexibility and reactivity of the data and its visualisations
4.	Engaging the reader to explore these visualisations on-demand within an RShiny app
5.	Drafting poster for an overview of the process from scoping to actual implementation of the RShiny app

## Using R to Visualise Spatio Temporal Data
### Overview on Previous Works
ABC

### What R Packages Will Be Used?
**Shiny:** The use of Shiny allows for greater interaction between the user and the dataset.  
**tmap** Use to plot thematic maps. Thematic maps are geographical maps in which spatial data distributions are visualized.   
**ggplot2:** Has a wide range of visualisations that can aid in analytics to understand the movement of the employees and the usage of credit card and loyalty data. Ggplot2 can be used for heatmap, timeseries and network graph visualisations.  
**tidyverse:** Manipulation of the three types of data (credit card, loyalty and GPS)   
**plotly** Use as a wrapper for ggplot2. Given the need for interactivity to identify the GASTech employees who made suspicious purchases and displayed abnormal patterns of behavior, plotly could be used for tooltips and annimations.  
**ggraph** Building on ggplot2, ggraph can provide greater detail and understanding of network data.  
**timetk** This package enables time-series visualisation. This includes anomaly detection and seasonality. This could facilitate the analysis to narrow down the suspicious employees.  


## Data Preparation  
Data preparation largely follows the Mini-Challenge questions posed:  

### 1. Data Cleaning
a. Check that dates are recognized correctly by R  
b. Check that location names are not mis-spelt that create duplicates redundancies  
c. For car-assignments data, replace car id blanks with 0 to indicate no car id.  

### 2. Merging Data
a. **Merging Credit Card And Loyalty Data To Form Transactional Dataset:** Transactional dataset formed by merging both the credit card and loyalty data by timestamp, location and amounts spent. To accommodate for possible errors in data inputs, we will use fuzzy matching to find the closest match between both datasets. This would give an indication of the loyalty number - credit card number relationship.
b. **Location of Owner Using GPS dataset:** Merge GPS dataset with car assignments dataset by ID.  This will give an indication of the employees's location by car assignment. Travel patterns of employees assigned vehicles could be used to identify suspicious behavior and narrow down the suspects. 
c. **Identifying Movements Through Merging GPS and Transactional Dataset:** First, we'll identify time pauses within the GPS data. Then we'll perform a visual inspection of these pauses in time and their respective locations vis-a-vis the map. From there, we can then match it against the transactional dataset to identify the car assignments.



## User Takeaways  
1.	**Allowing Users To Ask The Right Questions:** Manipulating the data in a form that can be visualized on an interactive platform would allow the user to explore the data in greater detail. For a visual detective, this is key in uncovering anomalies or trends into what might have happened prior to the disappearances.  
2.	**Giving Users The Dexterity To Explore A Hypothesis** TBC - For this case, timetk would help with...cross reference network analysis to .. 

## Assumptions  
1.	**Two Weeks Of Data Prior To The Disappearance Contains Valuable Clues:** The challenge only provides these two weeks worth of data and alludes that this dataset showcases suspicious behaviour that are related to the eventual disappearance. It is also possible to suggest that suspicious activities may have occurred outside of these two weeks.  
2.	**POI Locations Are Referenced Only From Map Image, And Not Through Exact Coordinates:** GPS movements through POI locations are visually approximated, after mapping the four corners of the map image onto a coordinate system. No availability of accurate POI coordinates.  

## Limitations  
1.	**Data Limited To Two Weeks Prior To Incident:** Apart from having data two weeks prior to the incident, obtaining data on the day of the incident would be equally, if not more, crucial in uncovering greater insights into what actually happened.  
2.	**[Limited Research](https://www-sciencedirect-com.libproxy.smu.edu.sg/science/article/pii/S1877584510000407) On How Errors In Attributes And Locations Influence Both Spatio-Temporal Assessment And Pattern Analysis:** The data extracted from the challenge has its own anomalies and its errors may skew its insights.   
3.  **Additional POIs Gleamed From GPS Data Missing From Map:** There are unknown POIs, derived from pauses in GPS data, that differ from the map. Though some POIs can be assumed as their residential points, other POIs would remain a mystery as to its actual nature.  

## Future Scope  
1. **Use Of Spatio-Temporal Statistics In Identifying Travel Patterns:** Using existing GPS data, we can work a model of how possible a person is likely to be at a particular place at a point in time, given their job position and time of day
2. **Time Series Anomaly Detection By Predictive Confidence Interval** Anomalies can be detected using time series modeling. Specifically, building a predictive model using to understand the common trend for each employee. The predictive model could forecast future values with a confidence band. One suggested approach is to use ARIMA for each employee.