stafflist <- c("IT Helpdesk Nils Calixto"="1",
               "Engineer Lars Azada"="2",
               "Engineer Felix Balas"="3",
               "SVP/CFO Ingrid Barranco"="4",
               "IT Technician Isak Baza"="5",
               "IT Group Manager Linnea Bergen"="6",
               "Drill Technician Elsa Orilla"="7",
               "IT Technician Lucas Alcazar"="8",
               "Drill Technician Gustav Cazar"="9",
               "SVP/CIO Ada Campo-Corrente"="10",
               "Hydraulic Technician Axel Calzas"="11",
               "Site Control Hideki Cocinaro"="12",
               "Site Control Inga Ferro"="13",
               "Engineering Group Manager Lidelse Dedos"="14",
               "Site Control Loreto Bodrogi"="15",
               "Perimeter Control Isia Vann"="16",
               "IT Technician Sven Flecha"="17",
               "Geologist Birgitta Frente"="18",
               "Hydraulic Technician Vira Frente"="19",
               "Building Control Stenig Fusil"="20",
               "Perimeter Control Hennie Osvaldo"="21",
               "Badging Office Adra Nubarron"="22",
               "Badging Office Varja Lagos"="23",
               "Perimeter Control Minke Mies"="24",
               "Geologist Kanon Herrero"="25",
               "Drill Site Manager Marin Onda"="26",
               "Drill Technician Kare Orilla"="27",
               "Drill Technician Isande Borrasca"="28",
               "Facilities Group Manager Bertrand Ovan"="29",
               "Security Group Manager Felix Resumir"="30",
               "President/CEO Sten Sanjorge Jr."="31",
               "SVP/COO Orhan Strum"="32",
               "Drill Technician Brand Tempestad"="33",
               "Perimeter Control Edvard Vann"="34",
               "Environmental Safety Advisor Willem Vasco-Pais"="35")

stafflist1 <- c("IT Helpdesk Nils Calixto",
               "Engineer Lars Azada",
               "Engineer Felix Balas",
               "SVP/CFO Ingrid Barranco",
               "IT Technician Isak Baza",
               "IT Group Manager Linnea Bergen",
               "Drill Technician Elsa Orilla",
               "IT Technician Lucas Alcazar",
               "Drill Technician Gustav Cazar",
               "SVP/CIO Ada Campo-Corrente",
               "Hydraulic Technician Axel Calzas",
               "Site Control Hideki Cocinaro",
               "Site Control Inga Ferro",
               "Engineering Group Manager Lidelse Dedos",
               "Site Control Loreto Bodrogi",
               "Perimeter Control Isia Vann",
               "IT Technician Sven Flecha",
               "Geologist Birgitta Frente",
               "Hydraulic Technician Vira Frente",
               "Building Control Stenig Fusil",
               "Perimeter Control Hennie Osvaldo",
               "Badging Office Adra Nubarron",
               "Badging Office Varja Lagos",
               "Perimeter Control Minke Mies",
               "Geologist Kanon Herrero",
               "Drill Site Manager Marin Onda",
               "Drill Technician Kare Orilla",
               "Drill Technician Isande Borrasca",
               "Facilities Group Manager Bertrand Ovan",
               "Security Group Manager Felix Resumir",
               "President/CEO Sten Sanjorge Jr.",
               "SVP/COO Orhan Strum",
               "Drill Technician Brand Tempestad",
               "Perimeter Control Edvard Vann",
               "Environmental Safety Advisor Willem Vasco-Pais")

colourlist <- c("Red"="red",
                "Blue"="blue",
                "Green"="green",
                "Black"="black",
                "Brown"="brown",
                "Grey"="grey",
                "Pink"="pink",
                "Violet"="violet",
                "Orange"="orange")

linetypelist <- c("Solid"="1",
                  "Dashed"="2",
                  "Dotted"="3",
                  "Dot-Dash"="4",
                  "Long-Dash"="5",
                  "Two-Dash"="6")






